import { createClient } from "contentful";
import Image from "next/image";
import Layout from "../../Components/Layout";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import DonateSnip from "../../Components/DonateSnip";
import Head from "next/head";

const renderOptions = {
  renderText: (text) => {
    return text.split("\n").reduce((children, textSegment, index) => {
      return [...children, index > 0 && <br key={index} />, textSegment];
    }, []);
  },
};

const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_KEY,
});

export const getStaticPaths = async () => {
  const res = await client.getEntries({
    content_type: "singleProject",
  });

  const paths = res.items.map((item) => {
    return {
      params: { slug: item.fields.slug },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const { items } = await client.getEntries({
    content_type: "singleProject",
    "fields.slug": params.slug,
  });

  return {
    props: { project: items[0] },
    revalidate: 1,
  };
};

export default function RecipeDetails({ project }) {
  const { title, description, thumbnail } = project.fields;

  return (
    <div>
      <Head>
        <title>WeRiseTogether - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <Layout>
        <section className="">
          <div className="flex flex-col">
            <div className="">
              <div className="h-80 relative">
                <Image
                  alt="content"
                  className="rounded-3xl h-full w-full"
                  objectFit="cover"
                  layout="fill"
                  src={"https:" + thumbnail.fields.file.url}
                />
              </div>
              <div className="flex flex-wrap w-full my-10">
                <div className="w-full">
                  <div className="sm:text-3xl text-2xl font-medium title-font mb-2">
                    {title}
                  </div>
                  <div className="h-1 w-20 bg-redBtn rounded"></div>
                </div>
              </div>
              <div className="text-base sm:text-xl leading-7 sm:leading-9 font-normal">
                {documentToReactComponents(description, renderOptions)}
              </div>
            </div>
          </div>
        </section>
        <DonateSnip />
      </Layout>
    </div>
  );
}
