import { createClient } from "contentful";
import Image from "next/image";
import Layout from "../../Components/Layout";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import DonateSnip from "../../Components/DonateSnip";
import Head from "next/head";
import Link from "next/link";

const renderOptions = {
  renderText: (text) => {
    return text.split("\n").reduce((children, textSegment, index) => {
      return [...children, index > 0 && <br key={index} />, textSegment];
    }, []);
  },
};

const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_KEY,
});

export const getStaticPaths = async () => {
  const res = await client.getEntries({
    content_type: "gallery",
  });

  const paths = res.items.map((item) => {
    return {
      params: { slug: item.fields.slug },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const { items } = await client.getEntries({
    content_type: "gallery",
    "fields.slug": params.slug,
  });

  return {
    props: { gallery: items[0] },
    revalidate: 1,
  };
};

export default function RecipeDetails({ gallery }) {
  const { title, pictures, reference } = gallery.fields;
  console.log(gallery);
  return (
    <div>
      <Head>
        <title>WeRiseTogether - {title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <div className="flex flex-wrap w-full mb-10">
          <div className="w-full mb-6">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Gallery - {title}
            </h1>
            <div className="h-2 w-20 bg-redBtn rounded"></div>
          </div>
        </div>
        <section className="grid gap-2 grid-cols-2 sm:grid-cols-3">
          {pictures.map((pictures) => (
            <Link
              href={"https:" + pictures.fields.file.url}
              key={pictures.fields.id}
            >
              <a target="blank">
                <div className="h-40 sm:h-80 relative">
                  <Image
                    alt="content"
                    className="rounded h-full w-full"
                    objectFit="cover"
                    layout="fill"
                    src={"https:" + pictures.fields.file.url}
                    alt={pictures.fields.title}
                  />
                </div>
              </a>
            </Link>
          ))}
        </section>
        <DonateSnip />
      </Layout>
    </div>
  );
}
