import Layout from "../Components/Layout";
import Link from "next/link";
import Image from "next/image";
import { createClient } from "contentful";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import Moment from "react-moment";
import Head from "next/head";

const renderOptions = {
  renderText: (text) => {
    return text.split("\n").reduce((children, textSegment, index) => {
      return [...children, index > 0 && <br key={index} />, textSegment];
    }, []);
  },
};

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: "singleProject" });

  return {
    props: {
      projects: res.items,
    },
  };
}

export default function Donate ({ projects }) {
  return (
    <div>
      <Head>
        <title>WeRiseTogether - Donate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <Layout>
        <section className="text-gray-600 body-font">
          <div className="">
            <div className="flex flex-wrap w-full mb-10">
              <div className="w-full mb-6">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
                  Donate Now
                </h1>
                <div className="h-2 w-20 bg-redBtn rounded"></div>
              </div>
              <p className="text-base sm:text-xl leading-7 sm:leading-9 font-normal">
                Hey, this is Shreya and I’m the founder WeRiseTogether. We are a
                non-profit organisation based in India working towards menstrual
                hygiene and provision of resources to underprivileged children
                under our #SheHygiene and #HelpingHands initiatives.
              </p>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 items-center gap-4 mt-7 sm:mt-12">
              <Link href="https://test.cashfree.com/billpay/product/1950">
                <a
                  className="font-medium text-2xl sm:text-4xl text-center rounded-xl py-5 leading-relaxed bg-gray-200"
                  target="blank"
                >
                  Rs 180
                </a>
              </Link>
              <Link href="https://test.cashfree.com/billpay/product/1950">
                <a
                  className="font-medium text-2xl sm:text-4xl text-center rounded-xl py-5 leading-relaxed bg-gray-200"
                  target="blank"
                >
                  Rs 350
                </a>
              </Link>
              <Link href="https://test.cashfree.com/billpay/product/1950">
                <a
                  className="font-medium text-2xl sm:text-4xl text-center rounded-xl py-5 leading-relaxed bg-gray-200"
                  target="blank"
                >
                  Rs 890
                </a>
              </Link>
              <Link href="https://test.cashfree.com/billpay/product/1950">
                <a
                  className="sm:col-span-3 font-medium text-2xl sm:text-4xl text-center rounded-xl py-5 leading-relaxed bg-redBtn"
                  target="blank"
                >
                  Custom
                </a>
              </Link>
            </div>
          </div>
        </section>
      </Layout>
    </div>
  );
}