import Head from "next/head";
import React from "react";
import { ToastContainer } from "react-toastify";
import Layout from "../components/Layout/Layout";
import Navbar from "../components/Navbar/Navbar";
import { createClient } from "contentful";
import Link from "next/link";
import background from "../public/donate.jpg"
import Image from "next/image";

export async function getStaticProps() {
	const client = createClient({
		space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
		accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_KEY,
	});

	const link = await client.getEntries({ content_type: "donationLink" });

	return {
		props: {
			links: link.items,
			revalidate: 10,
		},
	};
}

const Donate = ({ links }) => {
	console.log(links);
	return (
		<div>
			<Head>
				<title>We Rise Together</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
			<ToastContainer />
			<Navbar />
			<header className="h-[20rem] relative bg-slate-100 text-white mb-8">
				<Image
					src={background}
					alt="Thumbnail"
					layout="fill"
					objectFit="cover"
					objectPosition="center"
					className="z-0"
					priority
				/>
				<div className="z-10 backdrop-brightness-75 w-full h-full flex flex-col justify-center items-center">
					<h1 className="text-3xl md:text-5xl font-medium text-center p-4">Donate for a better future</h1>
				</div>
			</header>
			<Layout>
				<section className="grid grid-cols-1 md:grid-cols-2 gap-4">
					{Object.entries(links).map(([index, item]) => (
						<Link href={item.fields.link}>
							<a className={`btn ${index == 0 ? " border-transparent bg-red-primary" : " btn-outline"}`}>
								{item.fields.name}
							</a>
						</Link>
					))}
				</section>
			</Layout>
		</div>
	);
};

export default Donate;
