import Head from 'next/head';
import Layout from '../Components/Layout';
import Header from '../Components/Header';
import ProjectSnip from '../Components/ProjectSnip';

export default function Home() {
  return (
    <div>
      <div>
        <Head>
          <title>WeRiseTogether</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Layout>
            <Header />
            <ProjectSnip />
          </Layout>
        </main>
      </div>
    </div>
  );
}
