import Head from 'next/head';
import React from 'react'
import { ToastContainer } from 'react-toastify';
import { createClient } from "contentful";
import Layout from '../components/Layout/Layout';
import Navbar from '../components/Navbar/Navbar';
import Link from 'next/link';

export async function getStaticProps() {
	const client = createClient({
		space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
		accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_KEY,
	});

	const res = await client.getEntries({ content_type: "newsletter" });

	return {
		props: {
			newsletters: res.items,
			revalidate: 10,
		},
	};
}

const Index = ({ newsletters }) => {
	return (
		<div>
			<Head>
				<title>We Rise Together</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
			<ToastContainer />
			<Navbar />
			<Layout>
				<header className="py-8 flex flex-col gap-4">
					<h1 className="text-3xl font-medium text-red-primary">WRT Mirror</h1>
					<p>Check out our newsletter.</p>
        </header>
        
				<section>
					{newsletters != 0 ? (
						<div className="flex flex-col gap-4">
							{newsletters.map((newsletter) => (
								<Link
									key={newsletter.sys.id}
									newsletter={newsletter}
									href={"https:" + newsletter.fields.pdf.fields.file.url}>
									<a
										target="blank"
										className="p-4 flex flex-wrap gap-4 md:flex-nowrap border-2 border-black rounded-xl hover:bg-gray-100">
										<div className="md:flex-grow">
											<h2 className="text-xl font-medium text-[#fb5776] title-font mb-2">{newsletter.fields.title}</h2>
											<p className="prose line-clamp-2">{newsletter.fields.description}</p>
										</div>
									</a>
								</Link>
							))}
						</div>
					) : (
						<div className="p-4 border-2 border-black mt-4 rounded-xl text-center">No newsletters found</div>
					)}
				</section>
			</Layout>
		</div>
	);
};

export default Index