import Head from 'next/head';
import React from 'react'
import Layout from '../components/Layout/Layout';
import Navbar from '../components/Navbar/Navbar';
import { createClient } from "contentful";
import Image from 'next/image';

export async function getStaticProps() {
	const client = createClient({
		space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
		accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_KEY,
	});

	const team = await client.getEntries({ content_type: "team" });

	return {
		props: {
			team: team.items,
			revalidate: 10,
		},
	};
}

const Team = ({team}) => {
  return (
		<div>
			<Head>
				<title>We Rise Together</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>
			<Navbar />
			<Layout>
				<header className="py-8 flex flex-col gap-4">
					<h1 className="text-3xl font-medium text-red-primary text-center">Our Ambassadors</h1>
				</header>
				<section className="grid grid-cols-2 md:grid-cols-3 gap-4">
					{Object.entries(team).map(([index, member]) => (
						<div key={index} className="card shadow-md">
							<div className="aspect-square w-full relative">
								<Image
									src={`http:${member.fields.profilePicture.fields.file.url}`}
									layout="fill"
									objectFit="cover"
                  objectPosition="center"
                  alt='profile'
								/>
							</div>
							<h2 className="text-lg font-medium p-4 truncate text-center">{member.fields.name}</h2>
						</div>
					))}
				</section>
			</Layout>
		</div>
	);
}

export default Team